fjtsts/freemarket_sample_51e

app/views/items/_footer.html.haml
app/views/items/_header.html.haml
app/views/items/index.html.haml

#WHAT
header,footer部分テンプレート
＃WHY
viewの実装に必要なため

[WIP]render-header-footer

---

.gitignore
Gemfile
app/uploaders/image_uploader.rb
config/deploy.rb
config/initializers/carrierwave.rb
config/storage.yml

[WIP]Create S3

---

config/initializers/carrierwave.rb

[WIP]Update Carrierwave

---

config/initializers/carrierwave.rb

[WIP]Update Carrierwave.rb

---

.gitignore
config/credentials.yml.enc
config/deploy.rb
config/initializers/carrierwave.rb
config/storage.yml

strage.ymlがsecrets.ymlだと思っていたらcredentials.yml.encがsecrets.ymlの代わりだったので記載変更
S3の導入のからargument errorでデプロイできないため解消

[WIP]UpdateS3

---

app/views/layouts/application.html.haml

#WHAT
SEEDNにデーターを入れる
＃WHY
カテゴリーの管理に必要だから

[WIP] CREATED SEED

---

app/views/layouts/application.html.haml

Reverts fjtsts/freemarket_sample_51e#22

Revert "[WIP] CREATED SEED"

---

db/seeds.rb

#WHAT
seedを書いてデータベースに入れる
＃WHYカテゴリー一覧に必要なため

[WIP]Create seed

---

app/models/category.rb

#WHAT
category.rbのrelationの設定
＃WHY
カテゴリー一覧のため

[WIP]setting-relation-category

---

app/assets/stylesheets/users.scss
app/views/users/index.html.haml
app/views/users/show.html.haml

ユーザー個別ページの編集
(ソーシャルボタンの追加、評価アイコンの追加など)
ユーザビリティの向上

[WIP]ユーザー個別ページの編集

---

Gemfile.lock
app/controllers/users_controller.rb
app/models/address.rb
app/models/user_profile.rb
db/migrate/20190530095830_create_user_profiles.rb
db/migrate/20190530101502_create_addresses.rb
db/schema.rb
test/fixtures/addresses.yml
test/fixtures/user_profiles.yml
test/models/address_test.rb
test/models/user_profile_test.rb

user_profile
user_adress
モデルの作成
ユーザーの関連情報を保存するため

[WIP]ユーザーの関連モデルの作成

---

db/migrate/20190529095954_create_categories.rb
db/schema.rb

ユーザーモデルとプロフィール、住所を関連づける。
データを取り出せるようにするため。

[WIP]ユーザー登録に必要な情報のバリデーション

---

app/assets/stylesheets/_form-page-header&footer.scss
app/assets/stylesheets/_new_item_form.scss
app/assets/stylesheets/application.scss
app/views/items/new.html.haml
app/views/layouts/_form-page-footer.html.haml
app/views/layouts/_form-page-header.html.haml

#WHAT
出品ページのヘッダーとフッターの切り分け
#WHY
user/newでも使用するため

Create pull request

---

app/controllers/application_controller.rb
app/models/address.rb
app/models/user.rb
app/models/user_profile.rb
app/views/users/registrations/new.html.erb
app/views/users/sessions/new.html.erb
config/initializers/devise.rb

ユーザーモデルとアドレス、プロフィールにリレーションを設定する
ユーザーデータを取り出しやすくするため

[WIP]ユーザーモデルのリレーション設定

---

app/controllers/items_controller.rb
app/views/items/new.html.haml
app/views/layouts/form-layout.html.haml

#WHAT
出品ページのlayoutファイルのヘッダーとフッターを解除
#WHY
表示不要なので

[WIP]Create pull request

---

.gitignore

[WIP]create signin page

---

app/assets/javascripts/addresses.coffee
app/assets/javascripts/user_profiles.coffee
app/assets/stylesheets/addresses.scss
app/assets/stylesheets/user_profiles.scss
app/controllers/addresses_controller.rb
app/controllers/user_profiles_controller.rb
app/helpers/addresses_helper.rb
app/helpers/user_profiles_helper.rb
app/views/users/registrations/new.html.erb
config/routes.rb
test/controllers/addresses_controller_test.rb
test/controllers/user_profiles_controller_test.rb

ユーザー登録関連ページのフォームを仮で作成する
入力できるかの動作確認のため

[WIP]ユーザーページの仮作成(profiles and adress)

---

app/models/item_image.rb
db/migrate/20190601051519_create_item_images.rb
db/schema.rb
test/fixtures/item_images.yml
test/models/item_image_test.rb

＃WHAT
item_imageモデル作成
＃WHY
商品出品機能作成のため

[WIP]item_imageモデル作成

---

app/models/item_category.rb
app/models/item_image.rb

#WHAY
Write to image model
#WHY
Create sell function

[WIP]image model 

---

app/controllers/items_controller.rb
app/models/item.rb
app/models/item_image.rb
db/migrate/20190601051519_create_item_images.rb
db/schema.rb

#WHAT
Settings such as association and validation
#why
Create sell function

[WIP]Setting item model

---

app/controllers/items_controller.rb
app/models/category.rb
app/models/item.rb
db/seeds.rb

Association setting between item and category
Create sell function

[WIP]Association setting between item and category

---

app/assets/stylesheets/_purchases_new.scss
app/assets/stylesheets/application.scss
app/controllers/items_controller.rb
app/views/purchases/new.html.haml
config/routes.rb
db/schema.rb

商品購入確認ページのview実装
商品購入確認機能を実装するため

商品購入確認ページのマークアップ

---

app/assets/javascripts/user.js
app/assets/stylesheets/_form-page-header&footer.scss
app/assets/stylesheets/users.scss
app/controllers/users/registrations_controller.rb
app/controllers/users_controller.rb
app/views/layouts/_form-page-header-registration.html.haml
app/views/layouts/form-layout-registration.html.haml
app/views/users/new.html.haml
config/routes.rb
db/schema.rb

ユーザー新規登録ページのマークアップを行う
見た目を綺麗に整えて使いやすいようにするため

[WIP]ユーザー登録ページのマークアップ

---

app/assets/javascripts/item_view.js
app/assets/stylesheets/_items_show.scss
app/views/items/show.html.haml

各カテゴリのデータ呼び出し等
商品の詳細を確認することができるようにするため

[WIP]商品詳細ページのサーバーサイド作成

---

app/models/exhibit.rb
db/migrate/20190604094218_create_exhibits.rb
db/schema.rb
spec/factories/exhibits.rb
spec/models/exhibit_spec.rb

exhibitモデル作成
出品状態の管理、購入機能作成のため

[WIP]Create exhibit model

---

app/assets/javascripts/user.js
db/schema.rb

facebook google でのログイン機能の実装
簡単にログインできるようにするため

[WIP]SNSでのログイン

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/users/omniauth_callbacks_controller.rb
app/models/user.rb
app/views/users/new.html.haml
config/initializers/devise.rb
config/routes.rb
db/migrate/20190605062657_add_columns_to_users.rb
db/schema.rb

facebook
google
アカウントでログインできるようにする
簡単にログインできるようにするため

[WIP]SNSログインの実装

---

db/schema.rb

payjpを使ったクレジットカード機能の実装
商品決済できるようにするため

[WIP]クレジットカード機能の実装

---

Gemfile
Gemfile.lock
app/assets/javascripts/categories.coffee
app/assets/stylesheets/_mixins.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/categories.scss
app/assets/stylesheets/category-items.scss
app/assets/stylesheets/category-menue.scss
app/controllers/categories_controller.rb
app/helpers/categories_helper.rb
app/views/categories/index.html.haml
app/views/categories/show.html.haml
app/views/items/_category-menue.html.haml
app/views/items/_header.html.haml
config/breadcrumbs.rb
config/routes.rb
spec/controllers/categories_controller_spec.rb
spec/helpers/categories_helper_spec.rb

#WHAT 
カテゴ一覧ページ作成
＃WHY
カテゴリー検索を便利にするため

[WIP]category_index

---

app/controllers/items_controller.rb
app/models/brand.rb
app/models/category.rb
app/models/item.rb
app/views/items/index.html.haml
spec/controllers/items_controller_spec.rb
spec/factories/item.rb

[WHAT]
トップページビューアイテム一覧
アイテムコントローラーのindex記述
モデルのアソシエーション
indexページ変更
[WHY]
トップページの実装に必要だから

[WIP]トップページビューアイテム一覧

---

app/controllers/items_controller.rb
app/models/brand.rb
app/models/category.rb
app/models/item.rb
app/views/items/index.html.haml
spec/controllers/items_controller_spec.rb
spec/factories/item.rb

#WHAT
トップページビューアイテム一覧
#WHY 
実装に必要だから

Revert [WIP]トップページビューアイテム一覧

---

app/assets/stylesheets/header.scss
app/assets/stylesheets/pickup.scss
app/views/items/index.html.haml
spec/factories/brands.rb
spec/factories/category.rb

#WHAT 
z-indexを変更
＃WHY
他のビューに不具合が起きたため

[WIP]ビューの修正

---

app/controllers/application_controller.rb
app/controllers/items_controller.rb
app/controllers/users_controller.rb
app/views/users/_sidebar.html.haml
app/views/users/index.html.haml
app/views/users/logout.html.haml
app/views/users/show.html.haml
config/routes.rb

商品詳細ページにコメント機能を実装する
ユーザー同士のやりとりができるように

[WIP]コメント機能の実装

---

db/schema.rb

いいね機能の実装
他ユーザーとの交流、ブックマークの代わりとして使用するため

[WIP]Create IINE function

---

app/views/items/new.html.haml

image form

---

app/assets/stylesheets/_users_edit.scss
app/controllers/users_controller.rb
app/views/items/_header.html.haml
app/views/users/edit.html.haml
config/routes.rb

ユーザープロフィールのサーバーサイド
プロフィールを変更できるようにするため

ユーザープロフィール編集ページの機能実装 

---

app/assets/stylesheets/category-items.scss
app/assets/stylesheets/search.scss
app/controllers/application_controller.rb
app/controllers/categories_controller.rb
app/controllers/items_controller.rb
app/views/categories/show.html.haml
app/views/items/show.html.haml

Reverts fjtsts/freemarket_sample_51e#143

Revert "[WIP]ransackのエラー修正"
